### PR TITLE
[Fix] Missing no-cache profile in pom.xml

### PR DESCRIPTION
**Pull request by blcham**
Should fix issue with `mvn package` warning:
```
The requested profile "no-cache" could not be activated because it does not exists
```

### CODE REVIEW

**Comment by blcham** [comment]
> Should fix issue with `mvn package` warning:
> 
> ```
> The requested profile "no-cache" could not be activated because it does not exists
> ```

This issue is solely resolving warning in pom.xml as explained in the issue.  However, it is questionable whether it is useful to have "no-cache" profile in `pom.xml`. Considering [pull request in AL](https://github.com/opendata-mvcr/sgov-assembly-line/pull/93) it seems to me now that it make more sense to:
1. merge pull request https://github.com/opendata-mvcr/sgov-assembly-line/pull/93 
2. remove `-P no-cache` from [docker build](https://github.com/opendata-mvcr/termit/actions/workflows/build-docker.yml)
3. close this issue without merge

**Review by MichalMed — APPROVED** [review]
lg;tm

**Comment by MichalMed** [comment]
@blcham do as you wish, both PRs are approved, so merge one and close the other without merging as you wish.

**Comment by blcham** [comment]
I changed the build here: https://github.com/opendata-mvcr/termit/commit/5da58b4a7c629b27c8062e3e4c0b4979f69f3988
Thus closing this issue.

**Pull request closed without merging**
