### PR TITLE
Enhancement/85 subclassof broader

### LINKED ISSUE #85: Allow working with rdfs:subClassOf
As a user, I want TermIt to be able to work with rdfs:subClassOf. It should be a subProperty of skos:broader - this relationship should be reflected in the term hierarchy. I also want to be able to explicitly see and modify subclass relationship between terms.

### PR DESCRIPTION
**Pull request by ledsoft**
Resolves #85

### CODE REVIEW

**Review by psiotwo — DISMISSED** [review]
lgtm

**Comment by ledsoft** [comment]
Note that deployment requires adding "rdfs:subClassOf rdfs:subPropertyOf skos:broader" into the repository.

**Review by psiotwo — APPROVED** [review]
lgtm, without checking the functionality

**Comment by psiotwo** [comment]
> rdfs:subClassOf rdfs:subPropertyOf skos:broader

Shall we have some TTL with these triples to init the repo with?

**Comment by ledsoft** [comment]
I put the triple into termit-model.ttl

**Comment by psiotwo** [comment]
> I put the triple into termit-model.ttl

ah, ok, didn't notice.

**Pull request merged**
